version: "3.8"

networks:
  loki:
    driver: bridge

services:
  loki:
    image: grafana/loki:2.7.5
    ports:
    - 3100:3100  

    command:
    - -config.file=/etc/loki/local-config.yaml
    - -print-config-stderr=true  

    networks:
    - loki