version: "3.8"

networks:
  loki:
    driver: bridge

services:
  gerador-logs:
    image: keyssong/gera-log
    ports:
    - 8081:5000
    volumes:
    - "./logs/gerador-log:/logs" 
    networks:
    - loki  


  loki:
    image: grafana/loki:2.7.5
    ports:
    - 3100:3100  

    command:
    - -config.file=/etc/loki/local-config.yaml
    - -print-config-stderr=true  

    networks:
    - loki